server.port=5001
server.servlet.context-path=/nftheater-api
spring.output.ansi.enabled=ALWAYS
spring.application.name=nf-api

spring.datasource.url=jdbc:postgresql://localhost:5432/nftheater
spring.datasource.username=postgres
spring.datasource.password=p@ssw0rd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=5

#spring.datasource.url=jdbc:postgresql://ec2-52-206-14-156.compute-1.amazonaws.com/d3j77lk9m1hotm
#spring.datasource.username=veypupgpihlngi
#spring.datasource.password=14e41f17abf6be8869f6f1541f929b8734b2ce4297b7abc18c83b1810da21cc7
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jackson.time-zone=GMT+7
spring.mvc.format.date=yyyy-MM-dd
spring.sleuth.enabled=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} |%clr(%5p) | %clr(${spring.application.name}){green} | %X{IPAddress} | %X{traceId:-} | %X{spanId:-} | %clr(${PID}){magenta} %clr(---){faint} %clr([%7.15t]){faint} | %clr(%-10.40logger{10}:%L){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=1m

management.endpoints.web.exposure.include=prometheus,health,info,metric

line.bot.push.message.url=https://api.line.me/v2/bot/message
line.bot.channel-token=r8I8AHsGf07nScfQSSXG6vPlHA9y6mo+K/s6IqV7sXMyTX5dfIVhGotecDnugCe3XyF1N4Z3Ooh6pGFPET1V9M35Dd3IZCP+HzlhgMOIA3zE6W+lYhBd2TsWbGVS+tco6/mZNUuQjAMg7UrrrQgfHwdB04t89/1O/w1cDnyilFU=
line.bot.channel-secret=413a304503b49efdaa0f17a55d58a56d

thai.bulk.sms.url=https://otp.thaibulksms.com/v2/otp
thai.bulk.sms.app.key=1785602516757682
thai.bulk.sms.app.secret=ee4bd7fd26b29a29281f2f3d1af104c6
thai.bulk.sms.max.retry=3
thai.bulk.sms.cool.down.time=60

paysolution.service.url=https://apis.paysolutions.asia/secure/v3/secure/encryptz/
paysolution.merchant.id=30849104
paysolution.merchant.name=nftheater
paysolution.api.key=3KdNNgHd
paysolution.secret.key=bskids7GHcRCVPrW
paysolution.auth.key=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIyIiwiZXhwIjozMzAwNjk4Mzc3LCJpYXQiOjE3MjM4OTgzNzcsImp0aSI6IjE3MjM4OTgzNzdjZGY2MGYxM2Y2MWVkYzA0Nzc1ZTM4YTZiNTA3YTY2M2U1Mjk4MmJhYmRjZTNjMWRiOWEyNzMzZmFkMzUzNWJkNWZmOGRmIiwibmJmIjoxNzIzODk4Mzc3LCJzdWIiOiI0OTEwNCJ9.esXyeW8PbepjHIduITa0MmVKgQ7Zv7CuCSuOk1fuuMhEUuG8_UqiuMGHVIb_IQTf6F2uNakUisN41nXQh4QWwc3Ff_XRzRyt-qhC0Si2SGG7LkoL563rUD9kYZk6TW-9iCxFaOWUTWI1v3dEP3BWSYGHOb2_bUCW38WrJNmAX69jpsz9Fn_AGHjbdwqy4ToVBHi_OHZ3Hft4pDJhU__ExoYkJS8GwH8mGMnYN2eRu6L12YrcuInqPr7zOiQ_-DevG_beCUMrPlB-PdjzIjON2uXQZCnTYKZSrLwXz27ITLcsoj7bMyPLfgoyqv2OteOUrfIp5dYnJeVWCiSJXOmhpQ
paysolution.expired.duration=1d
paysolution.postback.url=https://nftheater-api-0c6adb473858.herokuapp.com/nftheater-api/v1/payment/callback
paysolution.return.url=https://nftheaterth.com/
paysolution.payment.url=https://pay.sn/